[package]
name = "omnimap"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/geo-mak/omnimap"

[dev-dependencies]
criterion = "0.8.1"

[[bench]]
name = "benchmarks"
harness = false
